version: '3'

# 名前つきボリューム
volumes:
  mysql_data:
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/api/'
    ports:
      - '3017:3017'
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3317:3317'
